server:
  port: 8888
spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    bus:
      trace:
        enable: true
    config:
      server:
        native:
          search-locations: classpath:/shared
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/